# Site settings
title: Ritam Raha
email: ritam.raha@uantwerpen.be
description: Ritam Raha's Homepage
baseurl: ""
url: ""


# Google analytics ID: Remove or use your own!
# google_analytics: UA-167467135-1
# google_analytics_4: G-02KDGRRB2T
# google_tag_manager: GTM-TZ9Z7HZ

# Footer info
affiliation: >
    Ritam Raha<br/>
    Doctoral Student in Computer Science<br/>
    <a href="https://www.uantwerpen.be/en/" target="_blank">University of Antwerp</a><br/>
    <a href="https://www.u-bordeaux.fr/" target="_blank">University of Bordeaux</a><br/>

location: >
  <a href="https://www.openstreetmap.org/?mlat=51.184253&;mlon=4.420946#map=18/51.18445/4.42103" target="_blank">Campus Middelheim</a><br/>
  University of Antwerp<br/>
  Middelheimlaan 1 <br/>
  M.G. 317<br/>
  2020 Antwerpen, België



contact: >
    <a href="mailto:ritam.raha@uantwerpen.be" target="_blank"><i class="fa fa-envelope fa-1x"></i> Contact Ritam via email</a> <br/>
    <a href="/aboutwebsite.html"><i class="fa fa-github fa-1x"></i> Use this site as a template!</a>

# Pages shown in navbar
nav_pages:
  - name: research
  - name: publications
  - name: talks
  - name: teaching
  - name: miscellaneous

include:
  - .htaccess
  - _pages

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
  parse_block_html: true # default for kramdown is false. This will enable using Markdown links


plugins: ['jekyll/scholar']

scholar:

  last_name: Raha 
  first_name: [R.]

  style: shb
  locale: en

  source: /cv/
  bibliography: ref.bib
  bibliography_template: bibtemplate
  #sort_by: year, month
  order: descending

  replace_strings: true
  join_strings: true

  details_dir: bibliography
  details_layout: bibtex.html
  details_link: Details

  query: "@*"

  bibliography_list_attributes:
    reversed: "reversed"

sass:
  sass_dir: _sass
  style: compressed

exclude:
  - Gemfile
  - Gemfile.lock
  - update_boostrap.sh
  - switch_theme.sh
  - tags
  - Rakefile
